telegram:
  bot_token: "YOUR_TELEGRAM_BOT_TOKEN"

defined_forum_themes:
  # Пример темы (форум / топик)
  - chat: 123321 # ID чата (группы)
    room: 1221   # ID топика (thread)

  # Можно добавить несколько
  - chat: 321123
    room: 2112

databases:
  mysql:
    host: "localhost"
    user: "dbuser"
    password: "dbpassword"
    dbname: "dbname"
